# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SWD_Monitor_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SWD_Monitor(object):
    def setupUi(self, SWD_Monitor):
        SWD_Monitor.setObjectName("SWD_Monitor")
        SWD_Monitor.resize(774, 594)
        self.centralwidget = QtWidgets.QWidget(SWD_Monitor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 10, 281, 551))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Receive_Window_Label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Receive_Window_Label.setFont(font)
        self.Receive_Window_Label.setObjectName("Receive_Window_Label")
        self.verticalLayout_2.addWidget(self.Receive_Window_Label)
        self.ReceivetextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.ReceivetextBrowser.setObjectName("ReceivetextBrowser")
        self.verticalLayout_2.addWidget(self.ReceivetextBrowser)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Clear_pushButton_Receive = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Clear_pushButton_Receive.setObjectName("Clear_pushButton_Receive")
        self.horizontalLayout_3.addWidget(self.Clear_pushButton_Receive)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(490, 11, 281, 551))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Analyz_Window_Label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Analyz_Window_Label.setFont(font)
        self.Analyz_Window_Label.setObjectName("Analyz_Window_Label")
        self.verticalLayout_3.addWidget(self.Analyz_Window_Label)
        self.AnalyzetextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        self.AnalyzetextBrowser.setObjectName("AnalyzetextBrowser")
        self.verticalLayout_3.addWidget(self.AnalyzetextBrowser)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.Clear_pushButton_Analyze = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.Clear_pushButton_Analyze.setObjectName("Clear_pushButton_Analyze")
        self.horizontalLayout_4.addWidget(self.Clear_pushButton_Analyze)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 191, 209))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.General_Setting_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.General_Setting_Label.setFont(font)
        self.General_Setting_Label.setObjectName("General_Setting_Label")
        self.verticalLayout.addWidget(self.General_Setting_Label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Port_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Port_Label.sizePolicy().hasHeightForWidth())
        self.Port_Label.setSizePolicy(sizePolicy)
        self.Port_Label.setMinimumSize(QtCore.QSize(23, 14))
        self.Port_Label.setMaximumSize(QtCore.QSize(23, 14))
        self.Port_Label.setObjectName("Port_Label")
        self.horizontalLayout_6.addWidget(self.Port_Label)
        self.PortInfo_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.PortInfo_Label.setText("")
        self.PortInfo_Label.setObjectName("PortInfo_Label")
        self.horizontalLayout_6.addWidget(self.PortInfo_Label)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.Port_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.Port_comboBox.setObjectName("Port_comboBox")
        self.verticalLayout.addWidget(self.Port_comboBox)
        self.BaudRate_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.BaudRate_Label.setObjectName("BaudRate_Label")
        self.verticalLayout.addWidget(self.BaudRate_Label)
        self.BaudRate_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.BaudRate_comboBox.setObjectName("BaudRate_comboBox")
        self.BaudRate_comboBox.addItem("")
        self.BaudRate_comboBox.addItem("")
        self.BaudRate_comboBox.addItem("")
        self.BaudRate_comboBox.addItem("")
        self.BaudRate_comboBox.addItem("")
        self.BaudRate_comboBox.addItem("")
        self.verticalLayout.addWidget(self.BaudRate_comboBox)
        self.Operation_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Operation_Label.setObjectName("Operation_Label")
        self.verticalLayout.addWidget(self.Operation_Label)
        self.Open_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Open_Button.setObjectName("Open_Button")
        self.verticalLayout.addWidget(self.Open_Button)
        self.Close_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Close_Button.setObjectName("Close_Button")
        self.verticalLayout.addWidget(self.Close_Button)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 220, 191, 161))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SWD_Setting_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SWD_Setting_Label.setFont(font)
        self.SWD_Setting_Label.setObjectName("SWD_Setting_Label")
        self.verticalLayout_4.addWidget(self.SWD_Setting_Label)
        self.Speed_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Speed_Label.setObjectName("Speed_Label")
        self.verticalLayout_4.addWidget(self.Speed_Label)
        self.Speed_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.Speed_comboBox.setObjectName("Speed_comboBox")
        self.Speed_comboBox.addItem("")
        self.Speed_comboBox.addItem("")
        self.Speed_comboBox.addItem("")
        self.Speed_comboBox.addItem("")
        self.Speed_comboBox.addItem("")
        self.Speed_comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.Speed_comboBox)
        self.SWD_Version_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.SWD_Version_Label.setObjectName("SWD_Version_Label")
        self.verticalLayout_4.addWidget(self.SWD_Version_Label)
        self.Version_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.Version_comboBox.setObjectName("Version_comboBox")
        self.Version_comboBox.addItem("")
        self.Version_comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.Version_comboBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 380, 191, 181))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.Statistics_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Statistics_Label.setFont(font)
        self.Statistics_Label.setObjectName("Statistics_Label")
        self.verticalLayout_5.addWidget(self.Statistics_Label)
        self.Number_Label_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.Number_Label_1.setObjectName("Number_Label_1")
        self.verticalLayout_5.addWidget(self.Number_Label_1)
        self.Number_textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_5)
        self.Number_textBrowser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.Number_textBrowser.sizePolicy().hasHeightForWidth())
        self.Number_textBrowser.setSizePolicy(sizePolicy)
        self.Number_textBrowser.setMinimumSize(QtCore.QSize(176, 13))
        self.Number_textBrowser.setMaximumSize(QtCore.QSize(139, 23))
        self.Number_textBrowser.setBaseSize(QtCore.QSize(139, 20))
        self.Number_textBrowser.setObjectName("Number_textBrowser")
        self.verticalLayout_5.addWidget(self.Number_textBrowser)
        self.Number_Label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.Number_Label_2.setObjectName("Number_Label_2")
        self.verticalLayout_5.addWidget(self.Number_Label_2)
        self.Number_textBrowser_2 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_5)
        self.Number_textBrowser_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.Number_textBrowser_2.sizePolicy().hasHeightForWidth())
        self.Number_textBrowser_2.setSizePolicy(sizePolicy)
        self.Number_textBrowser_2.setMinimumSize(QtCore.QSize(176, 13))
        self.Number_textBrowser_2.setMaximumSize(QtCore.QSize(139, 23))
        self.Number_textBrowser_2.setBaseSize(QtCore.QSize(139, 20))
        self.Number_textBrowser_2.setObjectName("Number_textBrowser_2")
        self.verticalLayout_5.addWidget(self.Number_textBrowser_2)
        self.Number_Label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.Number_Label_3.setObjectName("Number_Label_3")
        self.verticalLayout_5.addWidget(self.Number_Label_3)
        self.Number_textBrowser_3 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_5)
        self.Number_textBrowser_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.Number_textBrowser_3.sizePolicy().hasHeightForWidth())
        self.Number_textBrowser_3.setSizePolicy(sizePolicy)
        self.Number_textBrowser_3.setMinimumSize(QtCore.QSize(176, 13))
        self.Number_textBrowser_3.setMaximumSize(QtCore.QSize(139, 23))
        self.Number_textBrowser_3.setBaseSize(QtCore.QSize(139, 20))
        self.Number_textBrowser_3.setObjectName("Number_textBrowser_3")
        self.verticalLayout_5.addWidget(self.Number_textBrowser_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        SWD_Monitor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SWD_Monitor)
        self.statusbar.setObjectName("statusbar")
        SWD_Monitor.setStatusBar(self.statusbar)

        self.retranslateUi(SWD_Monitor)
        self.BaudRate_comboBox.setCurrentIndex(5)
        self.Version_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SWD_Monitor)

    def retranslateUi(self, SWD_Monitor):
        _translate = QtCore.QCoreApplication.translate
        SWD_Monitor.setWindowTitle(_translate("SWD_Monitor", "SWD_Monitor"))
        self.Receive_Window_Label.setText(_translate("SWD_Monitor", "Receive Window"))
        self.Clear_pushButton_Receive.setText(_translate("SWD_Monitor", "Clear"))
        self.Analyz_Window_Label.setText(_translate("SWD_Monitor", "Analyze Window"))
        self.Clear_pushButton_Analyze.setText(_translate("SWD_Monitor", "Clear"))
        self.General_Setting_Label.setText(_translate("SWD_Monitor", "General Settings"))
        self.Port_Label.setText(_translate("SWD_Monitor", "Port:"))
        self.BaudRate_Label.setText(_translate("SWD_Monitor", "Baud Rate:"))
        self.BaudRate_comboBox.setCurrentText(_translate("SWD_Monitor", "1000000"))
        self.BaudRate_comboBox.setItemText(0, _translate("SWD_Monitor", "9600"))
        self.BaudRate_comboBox.setItemText(1, _translate("SWD_Monitor", "19200"))
        self.BaudRate_comboBox.setItemText(2, _translate("SWD_Monitor", "38400"))
        self.BaudRate_comboBox.setItemText(3, _translate("SWD_Monitor", "57600"))
        self.BaudRate_comboBox.setItemText(4, _translate("SWD_Monitor", "115200"))
        self.BaudRate_comboBox.setItemText(5, _translate("SWD_Monitor", "1000000"))
        self.Operation_Label.setText(_translate("SWD_Monitor", "Operation"))
        self.Open_Button.setText(_translate("SWD_Monitor", "Open"))
        self.Close_Button.setText(_translate("SWD_Monitor", "Close"))
        self.SWD_Setting_Label.setText(_translate("SWD_Monitor", "SWD Settings"))
        self.Speed_Label.setText(_translate("SWD_Monitor", "Speed:"))
        self.Speed_comboBox.setItemText(0, _translate("SWD_Monitor", "100KHz"))
        self.Speed_comboBox.setItemText(1, _translate("SWD_Monitor", "500KHz"))
        self.Speed_comboBox.setItemText(2, _translate("SWD_Monitor", "1MHz"))
        self.Speed_comboBox.setItemText(3, _translate("SWD_Monitor", "2MHz"))
        self.Speed_comboBox.setItemText(4, _translate("SWD_Monitor", "4MHz"))
        self.Speed_comboBox.setItemText(5, _translate("SWD_Monitor", "6MHz"))
        self.SWD_Version_Label.setText(_translate("SWD_Monitor", "SWD Version:"))
        self.Version_comboBox.setCurrentText(_translate("SWD_Monitor", "Debug Interface v5.0"))
        self.Version_comboBox.setItemText(0, _translate("SWD_Monitor", "Debug Interface v5.0"))
        self.Version_comboBox.setItemText(1, _translate("SWD_Monitor", "Debug Interface v6.0"))
        self.Statistics_Label.setText(_translate("SWD_Monitor", "Statistics"))
        self.Number_Label_1.setText(_translate("SWD_Monitor", "Total Number of Frames:"))
        self.Number_textBrowser.setHtml(_translate("SWD_Monitor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.Number_Label_2.setText(_translate("SWD_Monitor", "Host Send Frames:"))
        self.Number_textBrowser_2.setHtml(_translate("SWD_Monitor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.Number_Label_3.setText(_translate("SWD_Monitor", "Host Receive Frames:"))
        self.Number_textBrowser_3.setHtml(_translate("SWD_Monitor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
